### ISSUE TITLE
Error finding "extra/wpmudev-dash-notification.php" line 44 domain-mapping.php

### ISSUE THREAD

**Issue by tnchuntic** [wpmudev/domain-mapping#1]
Hi just want to report an issue with this plugin. I have notice that the "extra/wpmudev-dash-notification.php" have been removed in the github.

On the domain-mapping.php line 44 it is "require_once 'extra/wpmudev-dash-notification.php';" the file.

Do I need to remove or comment out this code. 

Or it is really needed for the plugin to work?

Thanks

**Comment by ivan-ivanic-cm** [comment]
@tnchuntic Should be fixed now
